CREATE SEQUENCE ADDRESS_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE APP_USER_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE APPOINTMENTS_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE FICHAAVALIACAO_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE GENDER_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE ORGANIZATION_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE PERSONALACTIVITY_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE PERSON_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE PROFILE_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE PROFILEACCESS_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE ROLE_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE ROUTINE_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE SERVICETYPE_ID_SEQ START 1 INCREMENT 1;

CREATE SEQUENCE STATUSAGENDAMENTO_ID_SEQ START 1 INCREMENT 1;

CREATE TABLE ADDRESS (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   CITY VARCHAR(255),
   COMPLEMENT VARCHAR(255),
   DELETEDAT TIMESTAMP,
   NUMBER INT8,
   PUBLICPLACE VARCHAR(255),
   STATE VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   ZIPCODE VARCHAR(255),
   USERID INT8,
   USER_ID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE APP_USER (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   BOT BOOLEAN,
   CHANGEPASSWORD BOOLEAN,
   DELETEDAT TIMESTAMP,
   LOGIN VARCHAR(255) NOT NULL,
   PASSWORD VARCHAR(255) NOT NULL,
   PROFESSIONALNAME VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   UPDATEDBY VARCHAR(255),
   USER VARCHAR(255),
   ORGANIZATIONDEFAULTID INT8,
   PERSONID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE APPOINTMENTS (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   APPOINTMENTDATE DATE,
   APPOINTMENTTIME TIME,
   DELETEDAT TIMESTAMP,
   PERSONNAME VARCHAR(255),
   PREFERENCE BOOLEAN,
   PROFESSIONALNAME VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   APPOINTMENTSOLDID INT8,
   BOOKINGSTATUSID INT8,
   ORGANIZATIONID INT8,
   PERSONID INT8,
   PROFESSIONALID INT8,
   SERVICETYPE INT8,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE BOOKINGSTATUS (
   ID INT8 NOT NULL,
   STATUS VARCHAR(255),
   PRIMARY KEY (ID)
);

CREATE TABLE GENDER (
   ID INT8 NOT NULL,
   GENDER VARCHAR(255),
   PRIMARY KEY (ID)
);

CREATE TABLE ORGANIZATION (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   CELLPHONE VARCHAR(255),
   DELETEDAT TIMESTAMP,
   EMAIL VARCHAR(255),
   IDENTITYDOCUMENT VARCHAR(255),
   NAME VARCHAR(255),
   TELEPHONE VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   ADDRESSID INT8,
   PERSONAL_ACTIVITY_ID INT8,
   SERVICETYPE_ID INT8,
   USERID INT8,
   USER_ID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE PERSON (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   BIRTHDAY DATE,
   CELLPHONE VARCHAR(255),
   DELETEDAT TIMESTAMP,
   DOCUMENT VARCHAR(255),
   EMAIL VARCHAR(255),
   NAME VARCHAR(255),
   TELEPHONE VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   ADDRESSID INT8,
   GENEROID INT8,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE PERSONALACTIVITY (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   DELETEDAT TIMESTAMP,
   OCCUPATION VARCHAR(255),
   PERSONNAME VARCHAR(255),
   RESPONSIBLECONTACT VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   PERSONID INT8,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE PROFILE (
   ID INT8 NOT NULL,
   CREATEAT TIMESTAMP,
   FILEREFERENCE VARCHAR(255),
   FILESIZE INT8,
   KEYNAME VARCHAR(255),
   MIMETYPE VARCHAR(255),
   ORIGINALNAME VARCHAR(255),
   PERSONNAME VARCHAR(255),
   PERSONALACTIVITYID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE PROFILEACCESS (
   ID INT8 NOT NULL,
   CREATE BOOLEAN,
   DELETE BOOLEAN,
   NAME VARCHAR(255),
   READ BOOLEAN,
   UPDATE BOOLEAN,
   UPDATEDAT TIMESTAMP,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
   ID INT8 NOT NULL,
   ADMIN BOOLEAN,
   ROLE VARCHAR(255),
   USER_ID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE ROUTINE (
   ID INT8 NOT NULL,
   ICON VARCHAR(255),
   NAME VARCHAR(255),
   PATH VARCHAR(255),
   TITLE VARCHAR(255),
   UPDATEDAT TIMESTAMP,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE ROUTINEPROFILEACCESS (
   PROFILEACCESSID INT8 NOT NULL,
   ROUTINEID INT8 NOT NULL
);

CREATE TABLE SERVICETYPE (
   ID INT8 NOT NULL,
   SERVICETYPE VARCHAR(255),
   PRIMARY KEY (ID)
);

CREATE TABLE SERVICETYPEORGANIZATIONS (
   SERVICETYPEID INT8 NOT NULL,
   ORGANIZATIONID INT8 NOT NULL
);

CREATE TABLE SERVICETYPESUSERS (
   PROFESSIONALID INT8 NOT NULL,
   SERVICETYPEID INT8 NOT NULL
);

CREATE TABLE TASK (
   ID INT8 NOT NULL,
   ACTIVE BOOLEAN,
   AVALIATION VARCHAR(255),
   DELETEDAT TIMESTAMP,
   SUMMARY VARCHAR(255),
   TASK VARCHAR(255),
   TASKDATE TIMESTAMP,
   UPDATEDAT TIMESTAMP,
   PERSONALACTIVITYID INT8,
   USERID INT8,
   PRIMARY KEY (ID)
);

CREATE TABLE USERORGANIZATION (
   USERID INT8 NOT NULL,
   ORGANIZATIONID INT8 NOT NULL
);

CREATE TABLE USERROLES (
   USERID INT8 NOT NULL,
   ROLEID INT8 NOT NULL
);

CREATE INDEX IUSERAK1 ON APP_USER (PERSONID, LOGIN, ORGANIZATIONDEFAULTID, ACTIVE);

CREATE INDEX IAPPOINTMENTSAK1 ON APPOINTMENTS (APPOINTMENTDATE, APPOINTMENTTIME, PERSONID, PROFESSIONALID, ORGANIZATIONID, BOOKINGSTATUSID, ACTIVE);

CREATE INDEX IPERSONAK1 ON PERSON (NAME, TELEPHONE, CELLPHONE, BIRTHDAY, DOCUMENT, ACTIVE);

CREATE INDEX IPERSONALACTIVITYAK1 ON PERSONALACTIVITY (PERSONID, ACTIVE);

CREATE INDEX IFICHAAVALIACAOAK1 ON TASK (TASKDATE, PERSONALACTIVITYID, ACTIVE);

ALTER TABLE IF EXISTS ADDRESS ADD CONSTRAINT FKIGV0MCULVSDBSJ25SPUN5OVV5 FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ADDRESS ADD CONSTRAINT FKE4ETC0N243BR1D15PCMBT930W FOREIGN KEY (USER_ID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS APP_USER ADD CONSTRAINT FKPJN3Y2N1AXN7HUJK5BIJA9AX4 FOREIGN KEY (ORGANIZATIONDEFAULTID) REFERENCES ORGANIZATION;

ALTER TABLE IF EXISTS APP_USER ADD CONSTRAINT FKIQKSWJMTQNEO4QYLL8LU865E0 FOREIGN KEY (PERSONID) REFERENCES PERSON;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKTMWSBJWWHOMI9LD461F520HD0 FOREIGN KEY (APPOINTMENTSOLDID) REFERENCES APPOINTMENTS;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKLU4P4H5VFNBX3NQ4PVKUPMIYK FOREIGN KEY (BOOKINGSTATUSID) REFERENCES BOOKINGSTATUS;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FK77RPCEHA7DPE8OVDISWC0EKB4 FOREIGN KEY (ORGANIZATIONID) REFERENCES ORGANIZATION;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKML38U0JYKEI620YR6I3YP1CV2 FOREIGN KEY (PERSONID) REFERENCES PERSON;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKRFTGXHF6NMXU75AONABBO1WMC FOREIGN KEY (PROFESSIONALID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKA5EV07EJNNPMJJ600RI45VY83 FOREIGN KEY (SERVICETYPE) REFERENCES SERVICETYPE;

ALTER TABLE IF EXISTS APPOINTMENTS ADD CONSTRAINT FKKNSAJPU07OTWI7C9TEXGL7AXH FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ORGANIZATION ADD CONSTRAINT FKKWXRFY6DRW2U2U57THAWY3YC1 FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS;

ALTER TABLE IF EXISTS ORGANIZATION ADD CONSTRAINT FKKBGQVWFGNSP44HXYT2VJYTWBA FOREIGN KEY (PERSONAL_ACTIVITY_ID) REFERENCES PERSONALACTIVITY;

ALTER TABLE IF EXISTS ORGANIZATION ADD CONSTRAINT FK3F61SX00INMU4673A6JLPSHU5 FOREIGN KEY (SERVICETYPE_ID) REFERENCES SERVICETYPE;

ALTER TABLE IF EXISTS ORGANIZATION ADD CONSTRAINT FKPC5WHYTQBPBXCPYD9008IYS4O FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ORGANIZATION ADD CONSTRAINT FK8CGE1WRX5WRIWWILHLMT32UJX FOREIGN KEY (USER_ID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT FKF0H7AQCYNKCTW6MQ6B058Q6O7 FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS;

ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT FKHPNYLOPTJ1QBX64SSCFNG1JQ9 FOREIGN KEY (GENEROID) REFERENCES GENDER;

ALTER TABLE IF EXISTS PERSON ADD CONSTRAINT FKKKJ0QYKKHQGWOW8FXNDIX92FY FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS PERSONALACTIVITY ADD CONSTRAINT FKLGA9L4XC7K1OFW67LV8FLRJ90 FOREIGN KEY (PERSONID) REFERENCES PERSON;

ALTER TABLE IF EXISTS PERSONALACTIVITY ADD CONSTRAINT FKSU171INM186B5MNRJLXMLE27X FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS PROFILE ADD CONSTRAINT FKT1HGTNRLX0SWOKOHM9IENO4F7 FOREIGN KEY (PERSONALACTIVITYID) REFERENCES PERSONALACTIVITY;

ALTER TABLE IF EXISTS PROFILEACCESS ADD CONSTRAINT FK95R3O0JSS0IQIX9797O76DKIQ FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ROLE ADD CONSTRAINT FK4DHNTHKJEE7RC3SPNHU8ED3RC FOREIGN KEY (USER_ID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ROUTINE ADD CONSTRAINT FK35IHRTPJX8C8J26DX7TVNAFYW FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS ROUTINEPROFILEACCESS ADD CONSTRAINT FK84KLUSI0BMDI5CCGCXPWS2U5M FOREIGN KEY (ROUTINEID) REFERENCES ROUTINE;

ALTER TABLE IF EXISTS ROUTINEPROFILEACCESS ADD CONSTRAINT FKIYBB96WD7R665K7WKVW1CO85E FOREIGN KEY (PROFILEACCESSID) REFERENCES PROFILEACCESS;

ALTER TABLE IF EXISTS SERVICETYPEORGANIZATIONS ADD CONSTRAINT FK89DIEW1DM2ILC9LQP9CD1VV60 FOREIGN KEY (ORGANIZATIONID) REFERENCES ORGANIZATION;

ALTER TABLE IF EXISTS SERVICETYPEORGANIZATIONS ADD CONSTRAINT FKH8RHFMKL7LD8AHJ48RQP3OW4R FOREIGN KEY (SERVICETYPEID) REFERENCES SERVICETYPE;

ALTER TABLE IF EXISTS SERVICETYPESUSERS ADD CONSTRAINT FKCAL1GJ4I0GAJYLCOEKPFBJTUK FOREIGN KEY (SERVICETYPEID) REFERENCES SERVICETYPE;

ALTER TABLE IF EXISTS SERVICETYPESUSERS ADD CONSTRAINT FKMBUD71B01UBFMOB0WRJTT9US6 FOREIGN KEY (PROFESSIONALID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS TASK ADD CONSTRAINT FK577P2TN7UC72LATLUNJDOGL3S FOREIGN KEY (PERSONALACTIVITYID) REFERENCES PERSONALACTIVITY;

ALTER TABLE IF EXISTS TASK ADD CONSTRAINT FKK4F4ITLYKEV1J3XXOMS1C0JK0 FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS USERORGANIZATION ADD CONSTRAINT FKIHXV5Q1K4MFOM5SOJ5MJMYG6T FOREIGN KEY (ORGANIZATIONID) REFERENCES ORGANIZATION;

ALTER TABLE IF EXISTS USERORGANIZATION ADD CONSTRAINT FKC30QPFM1XV6PVBQT6AS0TQUM4 FOREIGN KEY (USERID) REFERENCES APP_USER;

ALTER TABLE IF EXISTS USERROLES ADD CONSTRAINT FKPYDUH9IA2FNX3O8PC3EILC3HA FOREIGN KEY (ROLEID) REFERENCES ROLE;

ALTER TABLE IF EXISTS USERROLES ADD CONSTRAINT FK1N0GI1R1B5ENQHQX3ORLTPB02 FOREIGN KEY (USERID) REFERENCES APP_USER;