name: Build Tests

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Build Postgres Database Container
        run: docker compose -f docker-compose.yml build redis

  quarkus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Build Quarkus Backend Container
        run: docker compose -f docker-compose.yml build quarkus

  telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Build API Telegram Container
        run: docker compose -f docker-compose.yml build telegram

  whatsapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Build API Whatsapp Container
        run: docker compose -f docker-compose.yml build whatsapp

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env.example
        run: cp .env.example .env

      - name: Build Frontend Container
        run: docker compose -f docker-compose.yml build frontend
